server:
  port: 8004

org:
  neo4j:
    driver:
      uri: neo4j://localhost:7687
      authentication:
        username: neo4j #default name. 따로 설정 안했으면 똑같이 적길 바람.
        password: insta-users #neo4j 데스크톱 콘솔에서 설정한 값

spring:
  application:
    name: follow-server

  data:
    neo4j:
      database: insta-users #neo4j 데스톱에서 만든 데이터베이스명

logging:
  level:
    org:
      springframework:
        data:
          neo4j: DEBUG # 내부적으로 돌아가는 native cyperQuery를 로그로 찍어줌

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true # 유레카 서비스에 (자신을) 등록 여부
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registryFetchIntervalSeconds: 10 # eureka에게 서비스 정보를 가져오는 주기
    disable-delta: true # eureka에게 서비스 정보를 가져올때 변경된 내용만 가져온다. (false로 하면 전체를 가져오기에 대역폭 낭비이다.

management:
  endpoints:
    web:
      exposure:
        include: "*"
